Feature/get vehicles
ynov-lyon-mobilite/easyselling-ios pull request #10
Opened 2021-10-25 17:55 UTC by Theo1998

2021-11-07 16:23 UTC, Theo1998 commented on easysellingTests/VehicleService_Specs.swift
> +        let users = getMockVehicles(token: "dzbsudqkghhgcvdsbv")
This function doesn't exists anymore

2021-11-07 16:23 UTC, Theo1998 commented on easyselling/Service/VehicleService.swift
> +    @Published var vehicules = [Vehicle]()
This class doesn't exists anymore

2021-11-07 16:23 UTC, Theo1998 commented on easyselling/Service/VehicleService.swift
> +
This class doesn't exists anymore

2021-11-07 20:50 UTC, MaxenceMottard requested changes

2021-11-07 20:50 UTC, MaxenceMottard commented on easyselling/Application/AppDelegate.swift
> +        let navigator = DefaultVehicleCreationNavigator(navigationController: navigationController)
Discard this change, it was just for test.

2021-11-07 20:50 UTC, MaxenceMottard commented on easyselling/Application/AppDelegate.swift
> +        let scenario = VehicleScenario(navigator: navigator)
Same

2021-11-07 20:50 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +struct Vehicle: Equatable, Decodable, Identifiable {
Move this struct in a `Vehicle.swift` file in `easyselling/Models/`directory

2021-11-07 22:40 UTC, nicolasbarb requested changes

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Application/Supporting Files/en.lproj/localizable.strings
> +"vehicles.moto" = "Moto";
motorcycle

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Models/Vehicle.swift
> +    var type: VehicleTypeEnum
Pas besoin de spécifié que c'est une enum dans son nom

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +    init(isOpenningVehicleCreation: @escaping Action,
met la callback en dernier dans la liste des paramètres

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +        self.apiCaller = DefaultAPICaller(urlSession: urlSession)
les services utilisés doivent être initialisé dans la définition du constructeur, pas dans ici (comme pour le request generator)

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +        // call api
Pas besoin de ces commentaires

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +        // fin du call
même chose sur le commentaires

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +            request = try requestGenerator.generateRequest(endpoint: .vehicles, method: .GET, headers: [:])
est-ce que c'est au viewModel d'avoir la responsabilité de créer une request, de la posséder et de faire un call API ?
Regarde sur les services qu'on à déjà pu faire, ce job est délégué à un service différent

2021-11-07 22:40 UTC, nicolasbarb commented on easysellingTests/Vehicle/MyVehicleViewModel_Spec.swift
>      func test_Opens_vehicle_creation_modal() {
Ce test à rien à faire ici, je crois que c'est moi qui l'avait fait à la base pour expliquer un truc à valentin.
dans tout les cas tu peux le supprimer

2021-11-07 22:40 UTC, nicolasbarb commented on easysellingTests/Vehicle/MyVehicleViewModel_Spec.swift
> +    func test_Shows_vehicle_when_request_is_success2() async {
Du coup tu peux enlever le 2 dans le nom du test et mettre un "s" à vehicle

2021-11-07 22:40 UTC, nicolasbarb commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +    @Published var isError: Bool = false
Etant donné que dans la view on affiche une alert le terme Alert serait plus approprié que error.

2021-11-07 22:40 UTC, nicolasbarb commented on easysellingTests/Vehicle/MyVehicleViewModel_Spec.swift
> +        thenGetError()
C'est pas très explicite comme fonction "thenGetError".
Si je dois faire des tests pour tout les types d'erreur aucun de mes tests passerait.
Fais des tests pour d'autres types d'erreur afin de refacto différement et de rendre tes tests plus lisibles

2021-11-08 06:32 UTC, MaxenceMottard approved these changes

2021-11-08 06:32 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
>  enum VehicleTypeEnum: String, Decodable {
You can also move this enum in `easyselling/Models/Vehicle.swift`

2021-11-09 04:44 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/MyVehicles/MyVehiclesViewModel.swift
> +            request = try requestGenerator.generateRequest(endpoint: .vehicles, method: .GET, headers: [:])
Voilà un exemple (n'oublie pas de tester cette classe aussi 😉) : https://github.com/ynov-lyon-mobilite/easyselling-ios/blob/develop/easyselling/Scenario/Authentication/AccountCreation/DefaultAccountCreator.swift

2021-11-11 15:17 UTC, nicolasbarb approved these changes

2021-11-11 15:55 UTC, merged