Vehicle Creation
ynov-lyon-mobilite/easyselling-ios pull request #15
Opened 2021-11-03 11:01 UTC by valmnt

2021-11-03 15:42 UTC, MaxenceMottard requested changes

2021-11-03 15:42 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/VehicleCreation/VehicleCreationView.swift
> +            VStack {
remove

2021-11-03 15:42 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/VehicleCreation/VehicleCreationView.swift
> +            VStack {
remove

2021-11-03 15:42 UTC, MaxenceMottard commented on easyselling/Scenario/Vehicles/VehicleScenario.swift
>      func goingBackToHomeView() {
use `@MainActor` instead of `DispatchQueue.main.async`

2021-11-03 16:49 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-04 09:12 UTC, PierreGourgouillon approved these changes

2021-11-04 09:14 UTC, PierreGourgouillon commented on easyselling/Scenario/Vehicles/VehicleCreation/VehicleCreationView.swift
> +            VStack {
Pourquoi il doit supprimer ca ?

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.emptyField.errorDescription ?? "")
Ton test ne doit pas avoir de expected nullable

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.incorrectYear.errorDescription ?? "")
même chose

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.incorrectLicense.errorDescription ?? "")
même chose

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +    func test_Shows_alert_when_an_error_happens_after_a_call_api() async {
after_an_api_call

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        givenViewModel(throwError: true)
Ce test est étrange et pas très explicite, assure toi que son contenu soit pas tester ailleurs déjà; dans ce cas ce test n'est pas utile

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +    func test_Shows_alert_when_the_creation_have_successful() async {
Est-ce que tu veux vraiment afficher une alerte quand l'utilisateur à réussi à créer un véhicule ? C'est bloquant non ?

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        if throwError {
Il y a besoin du if ?

2021-11-04 13:07 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreator_Specs.swift
> +            try await vehicleCreator.createVehicle(informations: VehicleInformations(license: "123456789", brand: "Audi", type: "car", year: "2005", model: "A1"))
ça serait bien de mettre les infos du véhicule en paramètre pour qu'on comprenne bien quel objet est envoyé au BO dans le test

2021-11-04 13:07 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
On a besoin du DispatchQueue ?

2021-11-04 20:52 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
Oui on fait un update de l'UI il faut donc que cela soit fait dans le thread principal : https://stackoverflow.com/questions/50245899/ios-swift-only-run-on-the-main-thread-error-for-app

2021-11-04 20:54 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
Et pas de @MainActor car c'est une fonction qui est passé en paramètre d'une autre et dans ce contexte @MainActor n'est pas le plus optimal

2021-11-04 20:58 UTC, valmnt commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +    func test_Shows_alert_when_the_creation_have_successful() async {
![Screenshot 2021-11-04 at 21 56 05](https://user-images.githubusercontent.com/46025586/140418724-8f61c082-01f8-49e6-a08b-96b7a9f9e51f.png)

Par simplicité, j'ai affiché le message à travers une popup mais quand on se concentrera sur l'UI alors on poourra faire autrement sans soucis.

2021-11-06 21:52 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-07 09:53 UTC, nicolasbarb requested changes

2021-11-07 09:53 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        givenViewModel(throwError: true)
Je sous entendais que tu ne dois pas passer dans ton givenViewModel un bool qui te dit si oui ou non tu affiches une erreur. Tu passes ton jeu d'information si tu en as besoin et c'est ton code de prod qui va venir afficher ou non une erreur, tu dois en aucun cas le préciser dans l'init de ton viewModel

2021-11-07 09:53 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleInformationsVerificator.swift
> +class VehicleInformationsVerificator: VehicleInformationsProtocol {
Ok donc sors les du viewModel, la classe doit être testée dans un fichier à part.

2021-11-07 09:53 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
Ok, on a quoi comme problème si on le met pas du coup ? Un warning ? une erreur ?

2021-11-07 09:53 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleCreationViewModel_Specs.swift
> +        if throwError {
C'est quoi ce cas précis ? Ton spy doit normalement pas avoir de logique, si tu veux qu'ils throw une erreur tout le temps dans ce cas là tu met pas de If.

2021-11-07 13:07 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
On ne respecte pas les recommandations Apple, on a donc un warning qui indique que les changements UI doivent se faire sur le thread principal.

2021-11-08 20:24 UTC, nicolasbarb requested changes

2021-11-08 20:24 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
Bah du coup pourquoi tu met pas @MainActor ? x)

2021-11-08 20:24 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleInformationsVerificator_Specs.swift
> +class VehicleInformationsVerificator_Specs: XCTestCase {
Ok pour ces tests mais il manque les tests qui s'assurent que les infos sont bonnes et ne retourne pas d'erreur ;)

2021-11-08 22:00 UTC, nicolasbarb requested changes

2021-11-08 22:00 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleInformationsVerificator_Specs.swift
> +        let message = whenChecking(vehicle: VehicleInformations(license: "123456789", brand: "brand", type: "type", year: "2005", model: "model"))
renomme message en quelque chose de plus explicite et de plus compréhensible (et surtout plus en lien avec le contexte)

2021-11-09 04:40 UTC, MaxenceMottard requested changes

2021-11-09 04:40 UTC, MaxenceMottard commented on easysellingTests/VehicleScenario_Specs/VehicleInformationsVerificator_Specs.swift
> +        let message = whenChecking(vehicle: VehicleInformations(license: "", brand: "brand", type: "type", year: "2005", model: "model"))
Regarde comment on a stocké ce genre de données dans les autres tests. Dans une variable de classe plutôt qu'une variable qui reste dans le scope de la fonction. C'est plus simple et plus lisible

2021-11-09 04:40 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            self.showAlert = true
Pourquoi `showAlert = true` alors que la request est un succès ?

2021-11-09 04:40 UTC, MaxenceMottard commented on easysellingTests/VehicleScenario_Specs/VehicleInformationsVerificator_Specs.swift
> +        let message = whenChecking(vehicle: VehicleInformations(license: "", brand: "brand", type: "type", year: "2005", model: "model"))
Tu peux voir un exemple ici : https://github.com/ynov-lyon-mobilite/easyselling-ios/blob/develop/easysellingTests/DefaultInformationVerificator_Specs/DefaultInformationsVerificator_Specs.swift

2021-11-09 07:48 UTC, valmnt commented on easysellingTests/VehicleScenario_Specs/VehicleInformationsVerificator_Specs.swift
> +        let message = whenChecking(vehicle: VehicleInformations(license: "", brand: "brand", type: "type", year: "2005", model: "model"))
Effectivement, c'est mieux je vais changer ça

2021-11-09 07:51 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            self.showAlert = true
Dans la description Trello de la tâche, il est demandé d'afficher un message lorsque la tâche succès. Comme on a dit qu'on ne se préoccupait pas du visuel, par simplicité je fais apparaitre un alert. Après quand on sera focus sur l'aspect visuel, je ferai autrement. Sauf si ça vous gêne et je peux afficher un texte dans la modal pour dire que la création a réussi.

2021-11-09 10:49 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            self.showAlert = true
Je pense qu'on peut simplement revenir en arrière pour retourner sur la list des véhicules (et la recharger bien sur). À voir ce qu'en pense @nicolasbarb

2021-11-09 10:53 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            self.showAlert = true
Je suis d'accord. De toute façon quand l'utilisateur verra que son nouveau véhicule apparait dans sa liste, ça lui suffira. Le plus important c'est d'afficher un message si une erreur survient.

2021-11-09 21:11 UTC, MaxenceMottard requested changes

2021-11-09 21:11 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreator.swift
>  class VehicleCreator: VehicleCreatorProtocol {
Désolé je rajoute un commentaire j'avais pas vu avant. Pour rester conforme à ce qu'on a fait dans les autres services. Il faut préfixer le nom de la classe par Default et ne pas suffixer le protocol.
Ce qui donne : 

```Swift
class DefaultVehicleCreator: VehicleCreator {
    ...
}
```

2021-11-14 08:27 UTC, MaxenceMottard requested changes

2021-11-14 08:27 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +            default: return vehicle
It's useless to return this information because you do not modify it in the function.

2021-11-14 08:27 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            let informationsVerified = try vehicleInformationsVerificator.verifyInformations(vehicle: informations)
remove return value

2021-11-14 08:27 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +        DispatchQueue.main.async {
Avec Nico, on est pas sur que tu ai besoin de mettre en DispatchQueue avec le navigationController.

2021-11-14 08:27 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesViewModel.swift
> +    @Published var vehicles: [VehicleInformations] = []
I prefer the model to be called "Vehicle". I've never seen a model called "UserInformations".

2021-11-14 08:48 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +            default: return vehicle
Nicolas m'a demandé de faire comme ça

2021-11-14 09:01 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            let informationsVerified = try vehicleInformationsVerificator.verifyInformations(vehicle: informations)
idem que la précédente

2021-11-14 10:00 UTC, MaxenceMottard approved these changes

2021-11-14 10:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +            default: return vehicle
Oui mais c'est inutile. Je lui faire le retour sur sa PR

2021-11-14 16:31 UTC, nicolasbarb approved these changes

2021-11-14 18:57 UTC, merged