Feature/forgot password
ynov-lyon-mobilite/easyselling-ios pull request #17
Opened 2021-11-04 14:24 UTC by nicolasbarb

2021-11-12 14:57 UTC, MaxenceMottard commented on easyselling/Application/SceneDelegate.swift
> +        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
You can remove this comments.

2021-11-14 16:56 UTC, MaxenceMottard approved these changes

2021-11-14 16:56 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/DefaultAuthenticationNavigator.swift
> +        DispatchQueue.main.async {
Is it required ?

2021-11-14 16:56 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/PasswordReset/Request/PasswordResetRequestViewModel.swift
> +            _ = try verificator.verify(email)
Don’t need to return value in verification

2021-11-14 16:56 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/PasswordReset/Reset/PasswordResetViewModel.swift
> +    private func setError(with error: CredentialsError) {
Is it really necessary ?

2021-11-14 16:56 UTC, MaxenceMottard commented on easysellingTests/DefaultAPICaller_Specs/SucceedingAPICaller.swift
> +    private(set) var isCallSucceed: Bool = false
Useless, if **call** function doesn’t throw any error, it means that is a success.

2021-11-14 16:57 UTC, MaxenceMottard requested changes

2021-11-14 16:57 UTC, MaxenceMottard commented on easyselling/Application/SceneDelegate.swift
> +
To comment to remove

2021-11-14 17:58 UTC, nicolasbarb commented on easysellingTests/DefaultAPICaller_Specs/SucceedingAPICaller.swift
> +    private(set) var isCallSucceed: Bool = false
j'ai oublié de le supprimer je m'en sers plus

2021-11-18 07:02 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/PasswordReset/Reset/DefaultPasswordResetTransformator.swift
> +        PasswordResetDTO(password: password, token: "")
On en arrive à faire une classe juste pour init un DTO. Je suis pas sûr que ce soit pertinent mais bon

2021-11-18 07:05 UTC, MaxenceMottard requested changes

2021-11-18 07:05 UTC, MaxenceMottard commented on easysellingTests/DefaultCredentialsVerificator_Specs/DefaultPasswordVerificator_Specs/DefaultPasswordVerificator_Specs.swift
> +            self.verifyingHasSucceed = true
Ça sert à rien, s’il n’y a pas d’errer c’est que c’est success

2021-11-18 07:05 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/PasswordReset/Reset/DefaultPasswordResetTransformator.swift
> +        PasswordResetDTO(password: password, token: "")
C’est un simple commentaire, si tu veux laisser ça comme ça 🤷🏼

2021-11-18 07:07 UTC, MaxenceMottard commented on easyselling/Scenario/Authentication/PasswordReset/Reset/DefaultPasswordResetTransformator.swift
> +        PasswordResetDTO(password: password, token: "")
C’est un simple commentaire, si tu veux laisser ça comme ça 🤷🏼

2021-11-20 14:46 UTC, nicolasbarb commented on easyselling/Scenario/Authentication/PasswordReset/Reset/PasswordResetViewModel.swift
> +    private func setError(with error: CredentialsError) {
Non mais j'aime bien mdr

2021-11-20 14:47 UTC, nicolasbarb commented on easyselling/Scenario/Authentication/PasswordReset/Reset/DefaultPasswordResetTransformator.swift
> +        PasswordResetDTO(password: password, token: "")
Pas besoin de tester ce genre de classe, tu peux intégrer directement le vrai service dans le test du dessous, mais ça évite à un service d'avoir une responsabilité qu'il doit pas avoir

2021-11-22 08:22 UTC, MaxenceMottard approved these changes

2021-11-22 08:26 UTC, MaxenceMottard approved these changes

2021-11-22 08:40 UTC, merged