Feature/on boarding
ynov-lyon-mobilite/easyselling-ios pull request #18
Opened 2021-11-06 21:14 UTC by PierreGourgouillon

2021-11-06 21:47 UTC, MaxenceMottard requested changes

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
Pourquoi créer un second AppDelegate alors qu’il y en avait déjà un ?

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/AppDelegate.swift
> +        onBoardingScenario.begin()
Je suis absolument pas d’accord sur le fait de passer par le scénario de OnBoarding a chaque fois qu’on démarre l’app alors qu’il n’apparaît que lors  de la première ouverture. C’est idiot de passer à un endroit inutile 99% du temps.

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Application/Supporting Files/Additions/Strings+Generated.swift
> +internal enum L10n {
Il ne faut pas commit ce fichier merci de le supprimer pour éviter tout conflit.

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Application/Supporting Files/Additions/XCAssets+Generated.swift
> +
Ne pas commit non plus

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Authentication/AuthenticationScenario_Specs.swift
> +class AuthenticationScenario_Specs: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Authentication/UserAuthenticationViewModel_Specs.swift
> +class UserAuthenticationViewModel_Specs: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Authentication/AccountCreationViewModel_Specs.swift
> +class AccountCreationViewModel_Specs: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Vehicle/MyVehicleViewModel_Spec.swift
> +class MyVehiclesViewModel_Spec: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Vehicle/VehicleCreationViewModel_Spec.swift
> +class VehicleCreationViewModel_Spec: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:47 UTC, MaxenceMottard commented on easyselling/Vehicle/VehicleScenario_Spec.swift
> +class VehicleScenario_Spec: XCTestCase {
Ce fichier n’a rien à faire ici. Il devrait être dans easellingTests

2021-11-06 21:48 UTC, MaxenceMottard commented
@PierreGourgouillon installe évitera d’avoir des erreurs de style pour rien alors que tu les vois dans Xcode

2021-11-06 23:10 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-06 23:27 UTC, nicolasbarb requested changes
Je viens de penser qu'en fait le bouton skip ne doit pas emmener à la dernière feature mais bien passer l'intégralité du onBoarding et direct le terminer. Il faudrait tester puis modifier ça.

Je n'ai vu aucune modif dans la modif de fichier (je l'ai ptetre raté) qui concerne le fait d'enlever le bouton de retour sur la page de connexion. Comment vous avez gérez ça ?

2021-11-06 23:27 UTC, nicolasbarb commented on easyselling/Application/Supporting Files/Assets.xcassets/menu.imageset/Contents.json
> +      "filename" : "menu.png",
C'est quoi cette image ?

2021-11-06 23:27 UTC, nicolasbarb commented on easyselling/Application/Supporting Files/Assets.xcassets/dotColorActive.colorset/Contents.json
> +        "color-space" : "srgb",
renomme cette couleur pour qu'elle soit le plus explicite possible, elle ne l'est pas assez.

2021-11-06 23:27 UTC, nicolasbarb commented on easyselling/Application/Supporting Files/Assets.xcassets/dotColorInactive.colorset/Contents.json
> +        "color-space" : "display-p3",
renomme cette couleur pour qu'elle soit le plus explicite possible, elle ne l'est pas assez.

2021-11-06 23:27 UTC, nicolasbarb commented on easysellingTests/OnBoardingScenario_Specs/OnBoardingScenario_Specs.swift
> +        spyNavigator.onFinish?()
refactor ceci

2021-11-06 23:27 UTC, nicolasbarb commented on easysellingTests/OnBoardingScenario_Specs/OnBoardingScenario_Specs.swift
> +        spyNavigator.onFinish?()
refactor ceci

2021-11-06 23:27 UTC, nicolasbarb commented on easysellingTests/OnBoardingScenario_Specs/OnBoardingViewModel_Specs.swift
> +    func test_Tries_to_go_to_next_feature_when_there_is_not_more() {
Does_nothing_when_trying_to_go_to_next_feature_when_on_the_last_feature

2021-11-06 23:27 UTC, nicolasbarb commented on easysellingTests/OnBoardingScenario_Specs/OnBoardingViewModel_Specs.swift
> +    func test_Clicks_on_skip_in_the_first_feature(){
test_Moves_to_last_feature_when_clicking_on_skip_button

2021-11-06 23:27 UTC, nicolasbarb commented on easyselling/Scenario/OnBoardingScenario/OnBoardingViewModel.swift
> +enum OnBoardingViewModelError : Error {
Cette enum sert à quelque chose ?

2021-11-07 06:08 UTC, MaxenceMottard commented
> Je viens de penser qu'en fait le bouton skip ne doit pas emmener à la dernière feature mais bien passer l'intégralité du onBoarding et direct le terminer. Il faudrait tester puis modifier ça.
> 
> Je n'ai vu aucune modif dans la modif de fichier (je l'ai ptetre raté) qui concerne le fait d'enlever le bouton de retour sur la page de connexion. Comment vous avez gérez ça ?

Ah oui, je trouvais ça bizarre moi aussi 👍🏽

2021-11-10 18:04 UTC, PierreGourgouillon commented
> @PierreGourgouillon installe évitera d’avoir des erreurs de style pour rien alors que tu les vois dans Xcode

2021-11-10 18:31 UTC, PierreGourgouillon commented
> > Je viens de penser qu'en fait le bouton skip ne doit pas emmener à la dernière feature mais bien passer l'intégralité du onBoarding et direct le terminer. Il faudrait tester puis modifier ça.
> > Je n'ai vu aucune modif dans la modif de fichier (je l'ai ptetre raté) qui concerne le fait d'enlever le bouton de retour sur la page de connexion. Comment vous avez gérez ça ?
> 
> Ah oui, je trouvais ça bizarre moi aussi 👍🏽

2021-11-10 21:34 UTC, nicolasbarb submitted a review, later dismissed

2021-11-10 21:36 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-10 21:49 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-10 21:53 UTC, MaxenceMottard submitted a review, later dismissed

2021-11-10 21:53 UTC, nicolasbarb approved these changes

2021-11-10 22:00 UTC, nicolasbarb approved these changes

2021-11-10 22:00 UTC, MaxenceMottard approved these changes

2021-11-10 22:01 UTC, merged