upload file request
ynov-lyon-mobilite/easyselling-ios pull request #19
Opened 2021-11-09 05:52 UTC by MaxenceMottard

# Conflicts:
#	easyselling.xcodeproj/project.pbxproj

2021-11-09 21:31 UTC, nicolasbarb requested changes

2021-11-09 21:31 UTC, nicolasbarb commented on easyselling/Services/DefaultFileUploader.swift
> +    init(requestGenerator: RequestGenerator = DefaultRequestGenerator(), urlSession: URLSessionProtocol = URLSession.shared) {
ça serait mieux de faire comme on a fait ailleurs, c'est à dire passer le defaultAPICaller en init plutôt que dans l'init

2021-11-09 21:31 UTC, nicolasbarb commented on easysellingTests/DefaultFileUploader_Specs/DefaultFileUploader_Specs.swift
> +    private func givenAccountCreator(error: APICallerError) {
Du coup le fait de passer APICAller en paramètre ça nous permettrait d'avoir quelque chose de plus lisible vis à vis de comment notre service réagis.
Genre on a un failingAPICaller donc on sait que notre système doit apprendre à réagir vis à vis d'une erreur retournée.

c'est juste pour la lisibilité et pour s'assurer qu'on init tout nos services de la même manière.

2021-11-09 21:49 UTC, MaxenceMottard commented on easyselling/Services/DefaultFileUploader.swift
> +    init(requestGenerator: RequestGenerator = DefaultRequestGenerator(), urlSession: URLSessionProtocol = URLSession.shared) {
On a déjà eu ce débat pour le UserAuthenticator et tu l'as validé 😓

2021-11-09 21:54 UTC, MaxenceMottard commented on easysellingTests/DefaultFileUploader_Specs/DefaultFileUploader_Specs.swift
> +    private func givenAccountCreator(error: APICallerError) {
Pareil c'est la 3e feature que je fais comme ça, et c'est relou d'avoir un retour que maintenant alors que je fais un copié collé de ce qui a été fait avant

2021-11-09 22:05 UTC, MaxenceMottard commented on easyselling/Services/DefaultFileUploader.swift
> +    init(requestGenerator: RequestGenerator = DefaultRequestGenerator(), urlSession: URLSessionProtocol = URLSession.shared) {
Pour moi ça permet de tester qu'avec un JSON donné on arrive bien à décoder dans le type que l'on veut. Ça fait un test supplémentaire mais bon ..

2021-11-10 20:53 UTC, CorentinLrcn submitted a review, later dismissed

2021-11-10 21:34 UTC, nicolasbarb submitted a review, later dismissed

2021-11-10 22:13 UTC, PierreGourgouillon approved these changes

2021-11-10 22:14 UTC, merged