Create InvoiceCreator request
ynov-lyon-mobilite/easyselling-ios pull request #20
Opened 2021-11-14 09:57 UTC by MaxenceMottard

2021-11-22 10:53 UTC, nicolasbarb requested changes

2021-11-22 10:53 UTC, nicolasbarb commented on easysellingTests/DefaultIInvoiceCreator_Specs/DefaultInvoiceCreator_Specs.swift
> +        let apiCaller = DefaultAPICaller(urlSession: FakeUrlSession(localFile: .userAuthenticatorResponse))
Un test avec le DefaultAPICaller ?

2021-11-22 10:53 UTC, nicolasbarb commented on easysellingTests/DefaultIInvoiceCreator_Specs/DefaultInvoiceCreator_Specs.swift
> +//        XCTAssertEqual(expectedRefreshToken, requestResult.refreshToken)
Du coup tu as finis les tests ou tu as besoin d'aide ?

2022-03-31 06:59 UTC, nicolasbarb requested changes

2022-03-31 06:59 UTC, nicolasbarb commented on easysellingTests/Services/DefaultIInvoiceCreator_Specs/DefaultInvoiceCreator_Specs.swift
> +        givenVehicleCreator(requestGenerator: FakeAuthorizedRequestGenerator(), apiCaller: SucceedingAPICaller())
Faut changer vehicle par invoice dans l'intégralité du fichier x)

2022-03-31 07:26 UTC, valmnt approved these changes

2022-03-31 07:30 UTC, nicolasbarb approved these changes

2022-03-31 07:30 UTC, merged