Feature/get invoices
ynov-lyon-mobilite/easyselling-ios pull request #24
Opened 2021-11-24 10:45 UTC by nicolasbarb

2021-12-04 11:13 UTC, MaxenceMottard requested changes

2021-12-04 11:13 UTC, MaxenceMottard commented on easyselling/Models/Invoice.swift
> +class Invoice : Codable, Equatable, Identifiable {
Use struct instead of class.
Here an article to understand differences between structs & classes : https://medium.com/@vinayakkini/swift-basics-struct-vs-class-31b44ade28ae

2021-12-04 11:13 UTC, MaxenceMottard commented on easyselling/Models/Invoice.swift
> +    var date_created : String
if you need help : https://blog.nicolas.brondin-bernard.com/convention-nommage-kebab-case-snake-case-et-autres/

2021-12-04 11:13 UTC, MaxenceMottard commented on easysellingTests/Invoice/InvoiceScenario_Specs.swift
> +class InvoiceService {
I don't understand what you wanted to do with this class but I think it's not the right way.

2021-12-04 11:13 UTC, MaxenceMottard commented on easysellingTests/Invoice/InvoiceScenario_Specs.swift
> +class InvoiceService {
and the InvoiceScenario is tested in `easysellingTests/InvoicesScenario_Specs/InvoicesScenario_Specs.swift` so what is the use of this test ?

2021-12-04 11:33 UTC, CorentinLrcn commented on easysellingTests/Invoice/InvoiceScenario_Specs.swift
> +class InvoiceService {
I thought I had deleted this file, it was an attempt and I created `easysellingTests/InvoicesScenario_Specs/InvoicesScenario_Specs.swift` to replace it

2021-12-04 11:34 UTC, CorentinLrcn commented on easysellingTests/Invoice/InvoiceScenario_Specs.swift
> +class InvoiceService {
I'll delete it right away

2021-12-04 11:48 UTC, CorentinLrcn commented on .bash_profile
> +alias xcode='open -a Xcode'
done

2021-12-04 11:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +    var date_updated : String?
done

2021-12-04 11:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +    var date_created : String
done

2021-12-04 11:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +class Invoice : Codable, Equatable, Identifiable {
done

2021-12-04 12:48 UTC, CorentinLrcn commented on .bash_profile
> +alias xcode='open -a Xcode'
done

2021-12-04 12:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +    var date_updated : String?
done

2021-12-04 12:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +    var date_created : String
done

2021-12-04 12:48 UTC, CorentinLrcn commented on easyselling/Models/Invoice.swift
> +class Invoice : Codable, Equatable, Identifiable {
done

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/DefaultVehicleInvoicesGetter_Specs.swift
> +    func test_Shows_error_when_request_failed() async {
ça serait plus test_Throws_error, parce que c'est le viewModel (donc le niveau + haut) qui aura la responsabilité d'afficher l'erreur à l'écran

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/DefaultVehicleInvoicesGetter_Specs.swift
> +class DefaultVehicleInvoicesGetter_Specs: XCTestCase {
Les tests me semblent ok mais tu as oublié de refactor pour qu'ils soit plus lisibles, prend exemple sur nos autres tests et refactor tes tests ;)

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/InvoicesScenario_Specs/VehicleInvoiceViewModel_Specs.swift
> +class SucceedingVehicleInvoicesGetter: VehicleInvoicesGetter {
Sors la class succeeding et failing dans des fichier séparé, on la fait dans les dossier de test des services

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/MyVehicleViewModel_Specs.swift
> +        viewModel.navigatesToInvoices(ofVehicle: "1")
Le test est pas mal mais il n'est pas forcément nécessaire car tu refais la même chose dans le test en dessous en mieux ;)

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/MyVehicleViewModel_Specs.swift
> +        viewModel.navigatesToInvoices(ofVehicle: "1")
N'oublie pas de refacto les tests avec un given / when / then

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/MyVehicleViewModel_Specs.swift
>          viewModel = MyVehiclesViewModel(vehiclesGetter: vehiclesGetter,
Réindente cette init stp

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +        navigator.onNavigatingToInvoices?("VehicleID")
Pareil n'oublie pas de refacto avec un given / when / then
Il peut y avoir plusieurs when ce qui correspond à une simple suite d'actions

2021-12-04 17:17 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +        thenHistory(is: [.myVehicles, .vehicleInvoices])
Plutôt que de tester l'historique dans ce cas là étant donné que tu changes complètement de scénario c'est mieux de tester que la callBack est bien appelé et qu'on passe bien à l'interieur

2021-12-05 15:38 UTC, CorentinLrcn commented on easysellingTests/VehicleScenario_Specs/MyVehicleViewModel_Specs.swift
> +        viewModel.navigatesToInvoices(ofVehicle: "1")
C'est toi qui les avait écrit ces tests x)

2021-12-05 19:32 UTC, nicolasbarb commented on easysellingTests/DefaultVehicleInvoicesGetter_Specs.swift
> +        thenReturnInvoices(expected)
Il faut vraiment que les tests soient lisibles comme un livre
ici ça serait plutot thenReturnedInvoices(are: expectedInvoices)

2021-12-05 19:32 UTC, nicolasbarb commented on easysellingTests/DefaultVehicleInvoicesGetter_Specs.swift
> +        thenError()
On doit pouvoir voir quel erreur est throw, là ton test marche pour une seule et unique erreur, si je le copie colle et que je met 500 comme erreur le test passera plus. on doit pouvoir lire et savoir qu'elle erreur ou quel message d'erreur sera throw

2021-12-05 19:32 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +        XCTAssertEqual("VehicleID", navigator.vehicleID)
utilise le paramètre de la fonction

2021-12-05 19:33 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/MyVehicleViewModel_Specs.swift
> +        viewModel.navigatesToInvoices(ofVehicle: "1")
C'était dans le but de t'expliquer la façon de faire du TDD.

2021-12-07 17:59 UTC, MaxenceMottard submitted a review, later dismissed

2021-12-07 19:02 UTC, CorentinLrcn approved these changes

2021-12-07 19:17 UTC, MaxenceMottard approved these changes

2021-12-07 19:17 UTC, merged