Feature/modify vehicle
ynov-lyon-mobilite/easyselling-ios pull request #25
Opened 2021-11-24 13:04 UTC by PierreGourgouillon

2021-11-24 13:49 UTC, nicolasbarb requested changes

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/DefaultVehicleNavigator.swift
> +        let vm = VehicleUpdateViewModel(vehicle: vehicle, onFinish: onFinish, vehicleVerificator: DefaultVehicleInformationsVerificator(), vehicleUpdater: DefaultVehicleUpdater())
Il faudrait passer les services Default directement dans l'init du viewModel

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesViewModel.swift
> +         isOpenningVehicleCreation: @escaping Action, isOpeningVehicleUpdate: @escaping OnUpdatingVehicle) {
petit saut de ligne après la virgule

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleUpdate/VehicleUpdateView.swift
> +
pas besoin de saut à la ligne

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleUpdate/VehicleUpdateView.swift
> +
pareil

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleUpdate/VehicleUpdateView.swift
> +
pareil

2021-11-24 13:49 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleUpdate/VehicleUpdateView.swift
> +
pareil

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +        await navigator.onFinish?()
refactor pls

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +        scenario.navigatesToVehicleUpdate(vehicle: Vehicle(id: "1", brand: "Peugeot", model: "model1", license: "license1", type: .car, year: "year1"))
il faudrait voir le véhicule passer en paramètre direct dans la fonction whenNavigating

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleScenario_Specs.swift
> +    func navigatesToHomeView(onVehicleCreationOpen: @escaping Action, onVehicleUpdateOpen: @escaping OnUpdatingVehicle) {
petit saut de ligne après la virgule

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +    private func thenAlertMessage(expected: String) {
thenAlertMessage(is expected: String)

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +    private func whenUpdateSuccesfull() async {
Succeed*

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.emptyField.description)
Il faudrait tester avec la valeur en string des erreurs

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.incorrectYear.description)
Pareil

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +        thenAlertMessage(expected: VehicleCreationError.incorrectLicense.description)
Pareil

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +    func test_Shows_alert_when_an_error_happens_after_an_api_call() async {
Ce test n'est plus utile vu que tu test l'équivalent plus haut

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +    func test_modifies_the_existing_vehicle() async {
Ce test est bizarre non ?

2021-11-24 13:49 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/VehicleUpdateViewModel_specs.swift
> +        viewModel = VehicleUpdateViewModel(vehicle: Vehicle(id: "1", brand: "Peugeot", model: "model1", license: "license1", type: .car, year: "year1"), onFinish: {
Il faudrait passer le vehicule en paramètre du given pour + de lisibilité

2021-11-25 17:20 UTC, MaxenceMottard requested changes

2021-11-25 17:20 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesView.swift
> +                        Button("Update") {
You have to use localizable files for strings

2021-11-25 17:20 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesView.swift
> +//struct MyVehiclesView_Previews: PreviewProvider {
Please uncomment this

2021-11-25 17:20 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesViewModel.swift
> +        self.isOpeningVehicleUpdate(vehicle, { await self.getVehicles() })
You need to test memory leak for `self.getVehicles()` method.
You can see with @nicolasbarb

2021-11-25 17:20 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleUpdate/VehicleUpdateViewModel.swift
> +    func deleteModal() async {
not necessary

2021-12-02 22:30 UTC, nicolasbarb submitted a review, later dismissed

2021-12-04 11:21 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleScenario.swift
> +import SwiftUI
Do you really need to import ‘UIKit’ & ‘SwiftUI’

2021-12-04 16:00 UTC, nicolasbarb approved these changes

2021-12-04 16:03 UTC, MaxenceMottard approved these changes

2021-12-04 16:04 UTC, merged