Feature/license-verification
ynov-lyon-mobilite/easyselling-ios pull request #26
Opened 2021-11-24 15:57 UTC by valmnt

2021-11-27 12:12 UTC, nicolasbarb requested changes
ça peut être intéressant de sortir la vérification de la plaque d'immatriculation dans un service externe.

Il faudrait aussi modifier le form de création de véhicule pour aider l'utilisateur à mettre un bon format de plaque d'immatricutlation.

2021-11-27 12:12 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +    func verifyLicenseSize(vehicle: Vehicle) -> Bool {
Ton système est peu explicite voir pas du tout compréhensible, on ne sait pas du tout ce que tu fais dans les fonctions.

Et à mon avis tu t'es pris la tête pour rien, deux simple Regex suffisait pour tester l'intégralité des cas, essayes de reprendre le système pour que ce soit  d'une part plus lisible et d'une autre plus simple

2021-11-27 12:12 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/DefaultVehicleInformationsVerificator_Specs.swift
> +    func test_Verifies_if_license_has_an_incorrect_format_for_old_license() {
Dans les tests on devrait voir des plaques d'immatriculation comme dans la vraie vie : "123 AAA 12", "AA-123-AA".
je pense pas que tes tests t'ai amené à faire le bon code de prod, essaye de les reprendre de manière à refacto la totalité

2021-11-27 15:33 UTC, valmnt commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +    func verifyLicenseSize(vehicle: Vehicle) -> Bool {
Effectivement avec les tests, j'ai carrément zappé le fait de pouvoir utiliser des regex pour me simplifier la tâche, my bad

2021-11-27 19:13 UTC, nicolasbarb commented on easyselling/Services/DefaultVehicleVerificator.swift
> +class DefaultVehicleVerificator: VehicleVerificator {
C'est clairement + lisible !
 Par contre pas sur que tu ai besoin de retourner des choses
 Inspire toi de ce que j'ai fait dans le EmailVerificator, PasswordVerificator et CredentialsVerificator

2021-11-27 19:13 UTC, nicolasbarb commented on easysellingTests/VehicleScenario_Specs/DefaultVehicleInformationsVerificator_Specs.swift
> +    func test_Verifies_message_if_year_has_an_icorrect_format() {
petite faute sur le mot incorrect ;)

2021-12-01 18:20 UTC, valmnt commented on easyselling/Services/DefaultVehicleVerificator.swift
> +class DefaultVehicleVerificator: VehicleVerificator {
J'ai besoin de retourner un bool pour savoir si je dois throw ou non une erreur.
Tu fais la même chose dans le DefaultEmailVerificator :

```
private func verifyContent(of mail: String) -> Bool {
    let emailPattern = #"^\S+@\S+\.\S+$"#
    let range = NSRange(location: 0, length: mail.utf16.count)

    guard let regex = try? NSRegularExpression(pattern: emailPattern),
          regex.firstMatch(in: mail, options: [], range: range) != nil else {
              return false
          }
    return true
}
```

La différence est que tu utilises des guard et moi un switch dans la fonction de verification.

2021-12-02 21:19 UTC, nicolasbarb commented on easyselling/Services/DefaultVehicleVerificator.swift
> +class DefaultVehicleVerificator: VehicleVerificator {
Regarde dans le DefaultCredentialVerificator je ne me sers pas de la valeur de retour dans la fonction publique, comme je t'ai dit je n'ai pas de valeur de retour.

2021-12-02 21:20 UTC, MaxenceMottard submitted a review, later dismissed

2021-12-04 11:25 UTC, MaxenceMottard approved these changes

2021-12-04 16:05 UTC, nicolasbarb approved these changes

2021-12-04 16:10 UTC, nicolasbarb approved these changes

2021-12-04 16:36 UTC, PierreGourgouillon approved these changes

2021-12-04 16:37 UTC, merged