Feature/persistent login
ynov-lyon-mobilite/easyselling-ios pull request #27
Opened 2021-11-24 16:34 UTC by Theo1998

2021-11-25 07:51 UTC, MaxenceMottard requested changes

2021-11-25 07:51 UTC, MaxenceMottard commented on easyselling/Application/SceneDelegate.swift
> +//        scenario.begin()
Please remove comments

2021-11-25 07:51 UTC, MaxenceMottard commented on easyselling/Scenario/OnBoardingScenario/OnBoardingScenario.swift
> +//        }
Please remove comments

2021-11-25 07:51 UTC, MaxenceMottard commented on easyselling/Services/DefaultTokenManager.swift
> +    func flush() {
Not used. Remove it

2021-11-25 07:51 UTC, MaxenceMottard commented on easyselling/Scenario/StartupScenario/StartupScenario.swift
> +    @MainActor func begin() async {
I asked you to refacto ..

2021-11-25 09:20 UTC, Theo1998 commented on easyselling/Scenario/StartupScenario/StartupScenario.swift
> +    @MainActor func begin() async {
I don't know how

2021-11-25 17:09 UTC, MaxenceMottard requested changes

2021-11-25 17:09 UTC, MaxenceMottard commented on easyselling/Services/DefaultTokenManager.swift
> +    func flush() {
You have resolve but it's not deleted

2021-11-26 08:03 UTC, MaxenceMottard approved these changes

2021-11-26 08:28 UTC, nicolasbarb requested changes

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +    func test_Begins_OnBoarding_scenario() async {
je trouve que ce test est franchement pas logique, il est censé tester que tu passes par le onBoarding, si c'est le cas ça veut dire que c'est la première fois que tu lances l'app et tu n'as du coup pas de Token donc il ne devrait pas y avoir de SucceedingTokenRefreshor.

Puis quand tu fais un givenOnBoardingViewed(is: false)  on est censé comprendre que tu pousses l'écran de onBoarding alors pourquoi il y a un bool à false en paramètre ?

Du coup je ne comprend pas bien le contenu du test vis à vis de son nom

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +    func test_Begins_OnBoarding_scenario() async {
Je pense que tu devrais reconstruite ton test pour qu'on comprenne plus simplement que tu lances l'app pour la première fois, donc tu dois parametrer ton given, when, then comme ci c'était un cas réel de première ouverture d'app.

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +    func test_Begins_OnBoarding_scenario() async {
Et pour finir le givenTokenManager il sert à quoi ? Parce que à l'intérieur tu passes un FakeTokenManager, du coup il est pas nil ?

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +    func test_Begins_OnBoarding_scenario() async {
Ce que tu cherches à faire est bon mais essaye de refacto stp

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +
Il manque un test pour la navigation entre le onBoarding, le login et les véhicules.
[.onBoarding, .login], [.onBoarding, .login, .vehicle]

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +    func test_Begins_Vehicle_scenario_If_Token_Expires() async {
Il faudrait indiquer dans le nom du test que tu t'attend à ce que le token soit refresh pour arriver à la page de vehicle

2021-11-26 08:28 UTC, nicolasbarb commented on easysellingTests/StartupScenario_Specs/StartupScenario_Specs.swift
> +
Dans l'ensemble tu as tester ce qu'il fallait sauf 2, 3 tests.
Il manque juste un poil de lisibilité pour qu'on comprenne vraiment rapidement ce qui se passe, essaye de relire tes tests comme ci tu n'avais pas écrit le code

2021-12-02 21:25 UTC, nicolasbarb approved these changes

2021-12-02 21:25 UTC, merged