Feature/delete vehicle
ynov-lyon-mobilite/easyselling-ios pull request #28
Opened 2021-11-25 09:01 UTC by Lucas-Barthelemy

2021-11-26 08:12 UTC, MaxenceMottard requested changes

2021-11-26 08:12 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesViewModel.swift
> +            } else {
this else is useless

2021-11-26 08:12 UTC, MaxenceMottard commented on easysellingTests/DefaultVehicleDeletor_Specs/SucceedingVehicleDeletor.swift
> +    func deleteVehicle(id: String) {
remove this useless function

2021-11-27 16:40 UTC, nicolasbarb approved these changes

2021-11-27 16:41 UTC, merged