Feature/watch an invoice
ynov-lyon-mobilite/easyselling-ios pull request #31
Opened 2021-12-05 19:25 UTC by nicolasbarb

2021-12-11 21:15 UTC, MaxenceMottard requested changes

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/DefaultInvoiceDownloader.swift
> +                                                                             headers: ["Content-Type": type],
Remove this, it's the type of the body, not the result type

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/DefaultInvoiceDownloader.swift
> +                                                                 headers: ["Content-Type": "application/json"],
Remove, it's automatically added by this class: https://github.com/ynov-lyon-mobilite/easyselling-ios/blob/develop/easyselling/Services/DefaultRequestGenerator.swift

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/InvoiceViewer/InvoiceView.swift
> +        VStack {
Why use this useless VStack with only one child ?

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/InvoiceViewer/InvoiceViewerViewModel.swift
> +    @Published var invoiceFile: File
Do you really need **@Published**? For me this should be a **let** variable

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/VehicleInvoicesView.swift
> +                            HStack {
Useless

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Services/DefaultAPICaller.swift
> +    func callImage(_ urlRequest: URLRequest) async throws -> UIImage {
This should not appear in api caller. It's only used by one service so it shouldn't be there.

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Services/DefaultAPICaller.swift
> +    func callImage(_ urlRequest: URLRequest) async throws -> UIImage {
Like this : https://github.com/ynov-lyon-mobilite/easyselling-ios/blob/develop/easyselling/Services/DefaultFileUploader.swift

2021-12-11 21:15 UTC, MaxenceMottard commented on easyselling/Services/DefaultAPICaller.swift
> +    func callImage(_ urlRequest: URLRequest) async throws -> UIImage {
Moreover, it is not the role of the service to convert data into UI

2021-12-11 21:20 UTC, nicolasbarb commented on easyselling/Scenario/InvoicesScenario/InvoiceViewer/InvoiceView.swift
> +        VStack {
Pour plus tard

2021-12-12 19:25 UTC, MaxenceMottard requested changes

2021-12-12 19:25 UTC, MaxenceMottard commented on easyselling/Services/DefaultAPICaller.swift
> +                print(data)
Remove

2021-12-12 19:25 UTC, MaxenceMottard commented on easysellingTests/DefaultAPICaller_Specs/FailingAPICaller.swift
> +import UIKit
Remove

2021-12-12 19:25 UTC, MaxenceMottard commented on easyselling/Scenario/InvoicesScenario/InvoiceViewer/InvoiceView.swift
> +        VStack {
Still useless

2021-12-14 13:06 UTC, MaxenceMottard approved these changes

2021-12-14 13:06 UTC, merged