Design/password reset
ynov-lyon-mobilite/easyselling-ios pull request #34
Opened 2021-12-10 20:30 UTC by nicolasbarb

2021-12-16 19:02 UTC, MaxenceMottard requested changes

2021-12-16 19:02 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/AccountCreation/AccountCreationView.swift
> +            GeometryReader { proxy in
Maybe create a component for background image. It's used 2 times

2021-12-23 10:10 UTC, MaxenceMottard submitted a review, later dismissed

2021-12-27 21:36 UTC, PierreGourgouillon commented on easyselling/Additions/UI/Components/ImagedBackground.swift
> +    init(@ViewBuilder contentBuilder: () -> Content) {
A quoi ca sert ?

2021-12-27 21:41 UTC, PierreGourgouillon commented on easysellingTests/ViewModels/Authentication/PasswordResetRequestViewModel_Specs.swift
> +//        await whenRequestingPasswordReset(of: "")
Tu ne delete pas ?

2021-12-27 21:42 UTC, PierreGourgouillon approved these changes

2021-12-27 21:42 UTC, nicolasbarb commented on easysellingTests/ViewModels/Authentication/PasswordResetRequestViewModel_Specs.swift
> +//        await whenRequestingPasswordReset(of: "")
Nan il faut que je trouve un moyen de faire passer ce test
Il est bon mais comme on fait du async await je trouve pas de moyen de faire ce que je veux

2021-12-27 21:42 UTC, merged