Feature/handle server errors
ynov-lyon-mobilite/easyselling-ios pull request #38
Opened 2021-12-15 16:02 UTC by valmnt

2021-12-15 18:09 UTC, nicolasbarb requested changes

2021-12-15 18:09 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +    func handleServerError(with body: ServerErrorBody) throws {
La fonction doit être private

2021-12-15 18:09 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +        switch body.extensions.code {
Refacto ce switch comme on a fait ligne 66 avec la fonction APICallerError.from() ;)

2021-12-15 18:09 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +struct ServerErrorResponse: Decodable {
Tu peux imbriquer ces structs plutot que les faire de façon séparer, ça evitera de les appeler sans faire expres dans l'app alors qu'elles sont utilisé qu'a un seul endroit

2021-12-15 18:09 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +struct ServerErrorResponse: Decodable {
Potentiellement tu peux aussi faire de la struct ServerErrorResponse une fileprivate ? je sais pas si ça fonctionne

2021-12-15 18:09 UTC, nicolasbarb commented on easysellingTests/FakeURLSession.swift
> +    init(){}
petit espace après les ()

2021-12-15 18:09 UTC, nicolasbarb commented on easyselling/Additions/Enums/ServerError.swift
> +enum ServerError: String, LocalizedError, Equatable {
En vrai rajoute le cas des invalids credentials et tu met comme phrase "L'email ou le mot de passe ne sont pas bons"
Je pense que c'est ok niveau criticité comme message

2021-12-17 16:29 UTC, valmnt commented on easyselling/Services/DefaultAPICaller.swift
> +    func handleServerError(with body: ServerErrorBody) throws {
Du coup comment peut-on tester une fonction private ?

2021-12-17 16:46 UTC, valmnt commented on easyselling/Services/DefaultAPICaller.swift
> +struct ServerErrorResponse: Decodable {
idem comment tester quelque chose de private ?

2021-12-21 19:02 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +struct ServerErrorResponse: Decodable {
My bad j'avais pas vu que tu avais fait un test avec

2021-12-21 19:05 UTC, nicolasbarb commented on easyselling/Services/DefaultAPICaller.swift
> +    func handleServerError(with body: ServerErrorBody) throws {
Dans ton test tu dois pas tester directement handleServerError
Tu dois t'assurer que avec la réponse obtenu on throw bien l'erreur que tu veux, la tes tests ils fonctionnent mais ils testent une partie de la logique qui normalement devrait être privé et interne au DefaultAPICaller

2021-12-27 19:17 UTC, nicolasbarb approved these changes

2021-12-27 19:17 UTC, merged