Design/update error
ynov-lyon-mobilite/easyselling-ios pull request #45
Opened 2022-01-22 12:06 UTC by nicolasbarb

2022-03-07 13:36 UTC, MaxenceMottard requested changes

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/ImagedBackground.swift
> +            Color.backgroundColor
Maybe use `.background` modifier ?

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Additions/Extensions/View+Extensions.swift
> +    }
```suggestion

    func ableToShowError(_ error: Error?) -> some View {
        modifier(ErrorShower(error: Error?))
    }
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/ErrorShower.swift
> +    var isShowingError: Bool
```suggestion
    var error: Error?
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/ErrorShower.swift
> +                }
```suggestion
                if let error = error {
                    VStack {
                        Text(error.errorDescription)
                            .font(.headline)
                            .foregroundColor(.white)
                            .padding(25)
                    }
                    .frame(maxWidth: .infinity)
                    .background(Color.red)
                    .cornerRadius(30)
                    .padding(.top, 100)
                    .transition(.move(edge: .top))
                }
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/AccountCreation/AccountCreationView.swift
> +            .ableToShowError(viewModel.error?.errorDescription ?? "", when: viewModel.error == nil ? false : true)
```suggestion
            .ableToShowError(viewModel.error)
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/PasswordReset/Request/PasswordResetRequestView.swift
> +                         when: viewModel.error == nil ? false : true)
```suggestion
        .ableToShowError(viewModel.error)
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/PasswordReset/Request/PasswordResetRequestViewModel.swift
> +class PasswordResetRequestViewModel: NSObject, ObservableObject {
Really necessary ?

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/PasswordReset/Reset/PasswordResetView.swift
> +        .ableToShowError(viewModel.error?.errorDescription ?? "", when: viewModel.state == .error)
```suggestion
        .ableToShowError(viewModel.error)
```

2022-03-07 13:36 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/UserAuthentication/UserAuthenticationView.swift
> +            .ableToShowError(viewModel.error?.errorDescription ?? "", when: viewModel.error == nil ? false : true)
```suggestion
            .ableToShowError(viewModel.error)
```

2022-03-07 13:39 UTC, nicolasbarb commented on easyselling/Scenario/AuthenticationScenario/PasswordReset/Request/PasswordResetRequestViewModel.swift
> +class PasswordResetRequestViewModel: NSObject, ObservableObject {
i'm not sure

2022-03-07 15:27 UTC, MaxenceMottard submitted a review, later dismissed

2022-03-08 08:03 UTC, MaxenceMottard approved these changes

2022-03-08 08:42 UTC, merged