Design/create vehicle screen
ynov-lyon-mobilite/easyselling-ios pull request #49
Opened 2022-03-07 16:01 UTC by nicolasbarb

2022-03-31 14:27 UTC, Lucas-Barthelemy approved these changes, later dismissed

2022-03-31 14:27 UTC, Lucas-Barthelemy commented on easyselling/Additions/UI/Components/SearchBar.swift
> +                    Text("Cherchez un nom, modèle...").foregroundColor(Asset.Colors.primary.swiftUIColor)
Here why you don't use a string in localizable ?

2022-03-31 16:18 UTC, nicolasbarb commented on easyselling/Additions/UI/Components/SearchBar.swift
> +                    Text("Cherchez un nom, modèle...").foregroundColor(Asset.Colors.primary.swiftUIColor)
Un oublis ;)

2022-04-01 07:00 UTC, MaxenceMottard requested changes

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/SearchBar.swift
> +                        .onTapGesture {
Could you use a Button instead. There is an animation when tap on Butotn

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/VehicleComponent/VehicleFormButton.swift
> +struct VehicleFormButton: View {
I prefer to create [`ButtonStyle`](https://www.hackingwithswift.com/quick-start/swiftui/customizing-button-with-buttonstyle) instead of Button component.

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/VehicleComponent/VehicleFormButton.swift
> +    let isSelected: Bool
Can a button really be selected?

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/VehicleComponent/VehicleFormTextField.swift
> +struct VehicleFormTextField: View {
Use Style instead of Custom component : https://thehappyprogrammer.com/custom-textfield-in-swiftui

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Components/VehicleComponent/VehicleListElement.swift
> +        .onTapGesture {
Use Button instead of `onTapGesture`

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Additions/UI/Styles/Buttons/ToggleButtonStyle.swift
> +struct ToggleButtonStyle: ButtonStyle {
Nice !!! You use Button style. Great job 👍

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Application/Supporting Files/fr.lproj/localizable.strings
> +"createVehicle.licence" = "Licence";
same change with `en localizable`?

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/AuthenticationScenario/UserAuthentication/UserAuthenticationView.swift
> +                    .disableAutocorrection(true)
Good idea

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/StartupScenario/DefaultStartupNavigator.swift
> +//        scenario.begin()
Remove ?

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesView.swift
> +        .onAppear {
use Task modifier

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleInformationsVerificator.swift
> +            case .unchosenType: return "Vous devez choisir un type de véhicule"
Add to localizable

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationView.swift
> +extension Notification {
add to `Notification+Extensions.swift` file

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/VehicleCreationViewModel.swift
> +            case .year: return "Année d'immatriculation"
localizable

2022-04-01 07:00 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleCreator.swift
> +        }
useless do catch

2022-04-01 07:46 UTC, nicolasbarb commented on easyselling/Additions/UI/Components/VehicleComponent/VehicleFormButton.swift
> +    let isSelected: Bool
it's the equivalent of a custom toggle button

2022-04-01 12:59 UTC, MaxenceMottard commented on easyselling/Additions/Enums/APICallerError.swift
> +enum APICallerError: Int, LocalizedError, Equatable {
Beurk !!

2022-04-01 13:01 UTC, MaxenceMottard commented on easyselling/Scenario/VehiclesScenario/VehicleCreation/DefaultVehicleCreator.swift
> +            try await apiCaller.call(urlRequest)
wrong indent

2022-04-01 13:03 UTC, MaxenceMottard approved these changes, later dismissed

2022-04-02 13:02 UTC, MaxenceMottard approved these changes

2022-04-02 19:49 UTC, merged