Feature/create account
ynov-lyon-mobilite/easyselling-ios pull request #5
Opened 2021-10-14 10:03 UTC by nicolasbarb

2021-10-16 17:17 UTC, MaxenceMottard requested changes
Good job 👍🏽

2021-10-16 17:17 UTC, MaxenceMottard commented on easyselling/Scenario/AccountCreation/AccountCreationViewModel.swift
> +            self.state = .accountCreated
Weak self

2021-10-16 17:17 UTC, MaxenceMottard commented on easyselling/Scenario/AccountCreation/AccountCreationViewModel.swift
> +                self.showAlert = true
Weak self

2021-10-16 17:17 UTC, MaxenceMottard commented on easyselling/Scenario/AccountCreation/DefaultAccountCreator.swift
> +            return AnyPublisher(Empty())
Maybe choose a default error when it failed ??

2021-10-16 17:17 UTC, MaxenceMottard commented on easyselling/Application/Supporting Files/en.lproj/localizable.strings
>  "helloWorld" = "Hello World ! ";
Remove

2021-10-16 17:17 UTC, MaxenceMottard commented on easyselling/Application/Supporting Files/fr.lproj/localizable.strings
>  "helloWorld" = "Bonjour monde !";
Remove

2021-10-18 06:50 UTC, MaxenceMottard commented on easysellingTests/DefaultRequestGenerator_Specs/DefaultRequestGenerator_Specs.swift
>                                      body: body, headers: [:])
- doesn't require to be on multiple lines
- bad indentation

2021-10-18 19:05 UTC, PierreGourgouillon approved these changes
Good job

2021-10-19 18:22 UTC, merged