Feature/vehicle coredata
ynov-lyon-mobilite/easyselling-ios pull request #52
Opened 2022-03-25 10:13 UTC by valmnt

2022-03-31 07:22 UTC, nicolasbarb requested changes

2022-03-31 07:22 UTC, nicolasbarb commented on easysellingTests/FailingVehicleGetter.swift
> +        return []
Lorsque la récupération des véhicules fails ont renvois plus d'erreur ?

2022-03-31 07:22 UTC, nicolasbarb commented on easysellingTests/Scenario/VehicleScenario_Specs/Vehicle_Specs.swift
> +class Vehicle_Specs: XCTestCase {
Quel est le besoin de cette classe de test ?
A quoi est-elle lié ? à un viewModel, un service ?

Pas sur de comprendre l'objectif là

2022-03-31 07:22 UTC, nicolasbarb commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenSuccess(with: "1")
C'est quoi ce with: "1" ?

2022-03-31 07:22 UTC, nicolasbarb commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenError(is: .notFound, with: "1")
même chose

2022-03-31 07:22 UTC, nicolasbarb commented on easysellingTests/SucceedingVehicleGetter.swift
> +    var error: APICallerError?
Pourquoi rajouter une erreur dans le succeedingVehicleGetter alors qu'elle est pas utilisé ?

2022-03-31 07:34 UTC, valmnt commented on easysellingTests/FailingVehicleGetter.swift
> +        return []
Non, on renvoie les données de CoreData et on utilise la variable `error` de DefaultVehiclesGetter pour afficher un message.

2022-03-31 07:38 UTC, valmnt commented on easysellingTests/Scenario/VehicleScenario_Specs/Vehicle_Specs.swift
> +class Vehicle_Specs: XCTestCase {
Ca été décidé en amont, cette classe représente Vehicle dans l'application notamment lorsqu'on veut décoder du JSON ou manipuler de la données.

Cette classe comporte 3 méthodes qui permet de convertir un Vehicle en VehicleDTO et en VehicleCoreData car dans certains contextes le type Vehicle n'a pas lieu d'être notamment lors de la sauvegarde d'un véhicle en BDD ou quand on souhaite créer un véhicle.

2022-03-31 07:38 UTC, valmnt commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenSuccess(with: "1")
L'id du vehicule supprimé

2022-03-31 07:38 UTC, valmnt commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenError(is: .notFound, with: "1")
idem

2022-03-31 07:54 UTC, valmnt commented on easysellingTests/SucceedingVehicleGetter.swift
> +    var error: APICallerError?
Pour se plier aux règles du protocol VehicleGetter

2022-03-31 07:59 UTC, nicolasbarb commented on easysellingTests/Scenario/VehicleScenario_Specs/Vehicle_Specs.swift
> +class Vehicle_Specs: XCTestCase {
Ok mais ça c'est testé normalement en interne dans d'autre classe de test, quand par exemple tu fais un get vehicle normalement ton test doit inclure une transformation d'un DTO vers une struct simple, du coup le test de ta transfo se fait ici

Pas besoin de faire un test pour une struct comme ici

2022-03-31 08:02 UTC, nicolasbarb commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenSuccess(with: "1")
Ok alors il faudrait réfacto le thenSuccess parce que c'est pas parlant du tout actuellement.

Il faut un nom qui nous fasse comprendre que le véhicule avec X id est bien supprimé

2022-03-31 08:02 UTC, nicolasbarb commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenError(is: .notFound, with: "1")
même commentaire qu'au dessus

2022-04-03 18:47 UTC, nicolasbarb requested changes

2022-04-03 18:47 UTC, nicolasbarb commented on easyselling/Models/CoreData/Vehicle/Vehicle.swift
> +    func toDTO() -> VehicleDTO {
pas static ?

2022-04-03 18:47 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesView.swift
> +        .alert(isPresented: $viewModel.showAlert, content: {
Il ne devrait plus y avoir d'affichage d'alert dans la page de véhicule, si tu veux afficher une erreur intéressante tu utilises le modifier

2022-04-03 18:47 UTC, nicolasbarb commented on easyselling/Scenario/VehiclesScenario/MyVehicles/MyVehiclesViewModel.swift
> +                self.showAlert = true
Pourquoi afficher une alerte ?

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +        let vehicleGetter = DefaultVehiclesGetter(requestGenerator: FakeAuthorizedRequestGenerator(), apiCaller: FailingAPICaller(withError: 404), context: context)
refactor

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +        vehicles = try? await vehicleGetter.getVehicles()
refactor

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
>      func test_Throws_error_when_request_failed() async {
Du coup en expected tu as 3 véhicules mais tu throw une erreur ? Pas sur que ce test vérifie ce qu'il dit

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +        let vehicleGetter = DefaultVehiclesGetter(requestGenerator: FakeAuthorizedRequestGenerator(), apiCaller: DefaultAPICaller(urlSession: FakeUrlSession(localFile: .succeededVehicles)), context:
refactor

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +        vehicles = try? await vehicleGetter.getVehicles()
refactor

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +        let coreDataObjects = try? context.fetch(fetchRequest)
Du coup tu récupères bien des véhicules de l'API mais aussi de CoreData ? Pas sur que le nom de ton test soit parlant

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +    func givenContext() {
private func

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/DefaultVehiclesGetter_Specs.swift
> +    func givenCoreDataObject() {
private func

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/Scenario/VehicleScenario_Specs/DefaultVehicleCreator_Specs.swift
>      func test_Creates_vehicle_successful() async {
Du coup le test c'est de s'assurer que le véhicule est crée sur Core Data ou sur l'API ?
Et du coup quand le call API a raté on save quand même sur core data ? Le nom des tests manques de précision

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/Scenario/VehicleScenario_Specs/DefaultVehicleCreator_Specs.swift
> +        vehicleDTO = VehicleDTO(brand: "Audi", licence: "123456789", model: "A1", type: .car, year: "2005")
L'initiatialisation du véhicule DTO devrait pas être dans cette fonction. Il faudrait plutot le passer en paramètre de ton when directement

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/Scenario/VehicleScenario_Specs/DefaultVehicleUpdater_Specs.swift
> +        vehicleCoreData = VehicleCoreData(id: "1", brand: "Audi", licence: "123456783", model: "A2", type: Vehicle.Category.car.rawValue, year: "2004", in: context)
Pareil que le vehicleDTO

2022-04-03 18:47 UTC, nicolasbarb commented on easysellingTests/Services/DefaultVehicleDeletor_Specs/DefaultVehicleDeletor_Specs.swift
> +        thenVehicles(are: 2)
Ok il reste 2 véhicules, mais si on prend ce test uniquement et qu'on le lis sans regarder dans chaque fonction on sait pas combien il y a de véhicule à la base

2022-04-05 19:04 UTC, valmnt commented on easyselling/Models/CoreData/Vehicle/Vehicle.swift
> +    func toDTO() -> VehicleDTO {
Non on souhaite convertir un type Vehicle vers un type VehicleDTO du coup autant appliquer la modification sur l'objet courant par conséquence static ne fonctionne pas.

2022-04-05 20:02 UTC, valmnt commented on easysellingTests/Scenario/VehicleScenario_Specs/DefaultVehicleCreator_Specs.swift
>      func test_Creates_vehicle_successful() async {
Les deux. Non quand le call api a échoué on affiche une erreur.

2022-04-20 07:39 UTC, MaxenceMottard requested changes

2022-04-20 07:39 UTC, MaxenceMottard commented on easyselling/Models/CoreData/Vehicle/Vehicle.swift
> +    }
useless

2022-04-20 07:39 UTC, MaxenceMottard commented on easyselling/Models/CoreData/Vehicle/Vehicle.swift
> +    static func toCoreDataObject(vehicle: Vehicle, in context: NSManagedObjectContext) -> VehicleCoreData {
maybe remove vehicle parameter, remove static and use self instance of Vehicle

2022-04-20 07:39 UTC, MaxenceMottard commented on easyselling/Models/CoreData/Vehicle/Vehicle.swift
> +    static func toVehicle(vehicle: VehicleCoreData) -> Vehicle {
move this method in vehicleCoreData, remove parameter and use self

2022-04-20 07:39 UTC, MaxenceMottard commented on easysellingTests/Services/DefaultAPICaller_Specs/SucceedingAPICaller.swift
> +        return response
C'est pas beau 🤮

2022-04-20 09:52 UTC, nicolasbarb approved these changes

2022-04-20 09:54 UTC, MaxenceMottard approved these changes

2022-04-20 09:55 UTC, merged